name: 'Lint'
on: pull_request

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
